FROM golang:1.21 as builder

WORKDIR /app

COPY go.* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -v -o app

FROM builder as tester
# CMD ["sh", "-c", "go test -v -cover ./... > test_report.txt"]
CMD ["sh", "-c", "go test -v -cover ./... > /app/tests/test_report.txt"]